import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { ThemeProvider, useTheme } from "@/context/theme-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function LayoutWrapper({children}: {children: React.ReactNode}) {
  const { themeClass } = useTheme();
  return <body className={`${themeClass} ${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ThemeProvider>
        <LayoutWrapper>{children}</LayoutWrapper>
      </ThemeProvider>
    </html>
  );
}
